model_name : "GCN_java250_baseline"
n_seeds : 3

wandb : 
  log_wandb : False
  wandb_api_key : "None"
  project : "None"
  entity : "None"
  tags : ["Java250", "GCN", "baseline", "training"]
  log_model : False

data_module:
  dataset: "Java250"
  root: "java250_baseline/" 
  train_csv: "java250_baseline/split/train_ids_split.csv"
  valid_csv: "java250_baseline/split/valid_ids_split.csv"
  test_csv:  "java250_baseline/split/test_ids_split.csv"
  batch_size: 32
  num_workers: 4
  pin_memory: false
  persistent_workers: true
  in_memory: true

model_params : {
    "gnn_type": "GCN",
    "gnn_depth" : 8,
    "gnn_dim": 768,      
    "gnn_norm_type": "layer_norm",
    "gnn_activation":    "GELU",

    "node_type_key": "node_type_idx",
    "use_node_type": true,
    "pos_features_key": "positional_feats",
    "use_pos_features": true,
    "semantic_features_key" : "semantic_feats",
    "use_semantic_features": false,

    "semantic_features_dim": 768,
    "pos_features_dim": 32,
    "n_node_types": 250,

    "node_type_dim": 512,
    "fuser_dim": 512,
    "fusion_method": "gated",

    "cls_pooling_method" : "max",

    "dropout": 0.051781912061564864,       
    "weight_decay": 2.899348721415141e-05,
    "use_class_weight" : true,
    
    "lr": 7.46963779194744e-05,
    "div_factor": 10,
    "pct_start":  0.14321821561373188,
    "anneal_strategy": "cos"
    }
study:
  study_name : "GCN_java250_baseline"
  n_trials  : 40
  load_if_exists : true

trainer:
  accelerator: "gpu"
  devices: 1
  epochs: 40
  precision: "16-mixed"
  log_every_n_steps: 10
  gradient_clip_val: 3.0
  gradient_clip_algorithm: "norm"
  enable_progress_bar: true
  progress_bar_color: "green"

model :
  model_type: "GNN_Classifier"
  num_classes: 250 

early :
  early_monitor : "val_f1"
  early_mode : "max"
  early_patience : 5

ckpt : 
  ckpt_monitor : "val_f1"
  ckpt_mode : "max"
  ckpt_save_top_k : 1




