model_name : "GCN_devign_deepseek-coder-1.3b-base"
n_seeds : 3

wandb : 
  log_wandb : False
  wandb_api_key : "None"
  project : "None"
  entity : "None"
  tags : ["Devign", "GCN", "deepseek-coder-1.3b-base", "training"]
  log_model : false

data_module:
  dataset: "Devign"
  root: "devign_deepseek-coder-1.3b-base/" 
  train_csv: "devign_deepseek-coder-1.3b-base/split/train_ids_split.csv"
  valid_csv: "devign_deepseek-coder-1.3b-base/split/validation_ids_split.csv"
  test_csv:  "devign_deepseek-coder-1.3b-base/split/test_ids_split.csv"
  batch_size: 24
  num_workers: 4
  pin_memory: false
  persistent_workers: true
  in_memory: true


model_params : {
    "gnn_type": "GCN",
    "gnn_depth" : 8,
    "gnn_dim": 768,      
    "gnn_norm_type": "graph_norm",
    "gnn_activation":    "GELU",

    "node_type_key": "node_type_idx",
    "use_node_type": true,
    "pos_features_key": "positional_feats",
    "use_pos_features": true,
    "semantic_features_key" : "semantic_feats",
    "use_semantic_features": true,

    "semantic_features_dim": 2048,
    "pos_features_dim": 32,
    "n_node_types": 250,

    "node_type_dim": 512,
    "fuser_dim": 512,
    "fusion_method": "sum",

    "cls_pooling_method" : "max",

    "dropout": 0.016122128725400444,        
    "weight_decay": 0.0006153085601625311,
    "use_class_weight" : true,
    
    "lr": 6.804032387540254e-05,
    "div_factor": 10,
    "pct_start": 0.10393422419156506,
    "anneal_strategy": "cos"
    }


trainer:
  accelerator: "gpu"
  devices: 1
  epochs: 20
  precision: "16-mixed"
  log_every_n_steps: 10
  gradient_clip_val: 3.0
  gradient_clip_algorithm: "norm"
  enable_progress_bar: true
  progress_bar_color: "green"

model :
  model_type: "GNN_Classifier"
  num_classes: 2 


early :
  early_monitor : "val_auprc"
  early_mode : "max"
  early_patience : 5

ckpt : 
  ckpt_monitor : "val_auprc"
  ckpt_mode : "max"
  ckpt_save_top_k : 1





